// Turkish text for the quiz bank, keyed by question id. a[0] stays the correct answer. Written as natural Turkish
// from quiz.js, not word for word; terms the Turkish Web3 community uses in English stay in English.
(function (root) {
  'use strict';
  root.TD_QUIZ_TR = {
    // hoodi
    rlnc: {"q":"Optimum'un kalbindeki teknoloji olan RLNC'nin açılımı nedir?","a":["Random Linear Network Coding","Rapid Ledger Node Consensus","Recursive Lattice Number Cryptography","Reliable Layered Network Caching"],"why":"Random Linear Network Coding, bir mesajın parçalarını rastgele doğrusal kombinasyonlarla karıştırır. Alıcının belirli parçaları beklemesine gerek yok; yeterince bağımsız parça toplaması yetiyor."},
    notchain: {"q":"Optimum, kendi konsensüsü olan bir blockchain mi?","a":["Hayır, blockchain'lerin yanında, yayılım katmanında çalışan bir ağ","Evet, proof of stake bir layer 1","Evet, bir Ethereum rollup'ı","Ethereum'un konsensüsünün yerini alıyor"],"why":"Optimum'a göre ağ, blockchain'lerin yanında ve sadece yayılım katmanında çalışıyor: veriyi daha hızlı taşıyor ama işlemleri sıralamıyor, yürütmüyor."},
    noconsensus: {"q":"Ethereum'un mump2p kullanabilmesi için konsensüs kurallarında neyi değiştirmesi gerekir?","a":["Hiçbir şeyi, konsensüs değişikliği gerekmiyor","Bir hard fork yapması","Yeni bir blok boyutu limiti koyması","Proof of work'e geri dönmesi"],"why":"Optimum, \"No consensus changes\" ilkesini tasarımın temel noktalarından biri sayıyor. mump2p mesajların yolculuğunu hızlandırıyor; zincirin neyde uzlaştığına dokunmuyor."},
    sidecar: {"q":"Bir validator mump2p'yi nasıl çalıştırır?","a":["Mevcut Ethereum client'ının yanında sidecar olarak","Consensus client'ını değiştirerek","Yeni bir zincire geçerek","Sadece merkezi bir relay üzerinden"],"why":"mump2p, validator'ın zaten kullandığı client'ın yanında sidecar olarak çalışıyor; yani client değiştirmene gerek yok."},
    hoodi150: {"q":"Optimum'un paylaştığı rakamlara göre Hoodi testnet'inde ortalama blok yayılım süresi ne kadar?","a":["Yaklaşık 150 ms","Yaklaşık 4 saniye","Yaklaşık 12 saniye","Yaklaşık 1 ms"],"why":"Optimum, Hoodi'de ortalama blok yayılımının yaklaşık 150 ms olduğunu söylüyor; bu da ona göre Gossipsub'dan en az 6 kat daha hızlı demek."},
    // mainnet
    slot: {"q":"Ethereum'da bir slot, yani bloğun önerilip attestation'ların yapılması gereken zaman aralığı, ne kadar sürer?","a":["12 saniye","1 saniye","1 dakika","10 dakika"],"why":"Ethereum'da bir slot 12 saniye. Geç gelen blok, validator'ların attestation için ayırdığı süreden yer; yayılım hızının bu kadar önemli olmasının sebebi de bu."},
    // hoodi
    agnostic: {"q":"mump2p sadece Ethereum için mi geliştirildi?","a":["Hayır, Optimum'a göre baştan chain agnostic tasarlandı","Evet, sadece Ethereum'da çalışıyor","Sadece Bitcoin'de çalışıyor","Sadece Solana'da çalışıyor"],"why":"Optimum'a göre ağ en baştan chain agnostic olarak tasarlandı. Ethereum sadece yolculuğun başladığı yer."},
    // blob
    what: {"q":"mump2p ağda hangi verileri yayar?","a":["Bloklar, blob'lar ve işlemler","Sadece smart contract kodu","Sadece NFT görselleri","Private key'ler"],"why":"Dokümanlarda mump2p, blok, blob ve işlemlerin hızlı yayılması için RLNC ile hızlandırılmış bir pub/sub olarak geçiyor."},
    // flood
    compat: {"q":"mump2p hangi mevcut protokolle uyumlu olacak şekilde tasarlandı?","a":["libp2p Gossipsub","Kafka","MQTT","BitTorrent"],"why":"Dokümanlarda mump2p için libp2p ve Gossipsub uyumlu bir pub/sub yazıyor; yani Ethereum client'larının zaten kullandığı ağ katmanının yanına rahatça oturuyor."},
    fullcopies: {"q":"Klasik Gossipsub bir bloğu peer'lar arasında nasıl taşır?","a":["Mesajın tam kopyasını gönderir","Kodlu shard'lar gönderir","Veri değil, sadece bir hash gönderir","Her şeyi tek bir sunucudan geçirir"],"why":"Gossipsub mesajı bütün halinde iletir, bu yüzden aynı blok bir peer'a birkaç komşusundan birden gelir. Oyundaki Dupe'lar tam da bu tekrarlar."},
    dupuseless: {"q":"Bir bloğun kopyası neden bant genişliği israfıdır?","a":["Peer'a elinde olmayan hiçbir bilgi getirmez","Her zaman bozuk gelir","Yanlış anahtarla şifrelenmiştir","Orijinalinden büyüktür"],"why":"Aynı kopyanın ikincisi hiçbir şey katmaz. RLNC'de ise taze kodlu bir shard neredeyse her zaman yeni bilgi getirir, böylece boşa giden trafik azalır."},
    bw: {"q":"Optimum, Gossipsub'a kıyasla bant genişliğinde ne kadar tasarruf sağladığını söylüyor?","a":["Yaklaşık %90 ile %95 arası","Yaklaşık %10","Yaklaşık %50","Hiç, hız için bant genişliğinden feragat ediyor"],"why":"Optimum'a göre Gossipsub'dan yaklaşık %90 ile %95 arası daha az bant genişliği harcanıyor; bunun büyük kısmı gereksiz tam kopyaları göndermemekten geliyor."},
    // stress
    speedx: {"q":"Optimum, blok ve blob teslimatında Gossipsub'dan ne kadar hızlı olduğunu söylüyor?","a":["6 ile 20 kat arası daha hızlı","2 kat daha hızlı","100 kat daha hızlı","Aynı hızda, sadece daha ucuz"],"why":"Optimum, blok ve blob'ları Gossipsub'a göre 6 ile 20 kat arası daha hızlı ulaştırdığını söylüyor."},
    // flood
    idontwant: {"q":"IDONTWANT kontrol mesajının arkasındaki fikir ne?","a":["Peer'lara elinde zaten olan veriyi göndermemelerini söylemek","Ağdan ayrılmak istemek","Geçersiz bir bloğu reddetmek","Validator çıkışı talep etmek"],"why":"IDONTWANT ile bir peer o mesajın zaten elinde olduğunu söyler, komşuları da onu göndermeye zahmet etmez. mump2p de IDONTWANT, IHAVE ve IWANT kontrol mesajlarını kullanıyor."},
    // shard
    kshards: {"q":"Bir mesaj k parçaya bölünüp n shard'a kodlanıyor. Bir node'un mesajı yeniden oluşturması için kaç shard gerekir?","a":["Doğrusal olarak birbirinden bağımsız herhangi k shard","n shard'ın hepsi","Tam olarak ilk gönderilen k shard","2k shard"],"why":"Birbirinden bağımsız herhangi k kodlu shard yeter; hangilerinin geldiği fark etmez. Oyundaki kodlu kalkanların belirli ekip üyelerini değil, farklı ekip üyelerini istemesinin sebebi de bu."},
    shardfactor: {"q":"mump2p'de varsayılan shard factor (mesaj başına shard sayısı) kaç?","a":["4","1","16","64"],"why":"OPTIMUM_SHARD_FACTOR varsayılan olarak mesaj başına 4 shard."},
    threshold: {"q":"Bir mump2p node'u mesajı iletebilmek ya da çözebilmek için varsayılan olarak shard'ların ne kadarını toplamalı?","a":["%75","%100","%25","%50"],"why":"OPTIMUM_THRESHOLD varsayılan olarak 0.75. Node'lar her shard'ı beklemek yerine bu orana ulaştıkları anda harekete geçiyor."},
    shardmult: {"q":"mump2p'deki shard multiplier (varsayılanı 1.5) neyi belirler?","a":["Kaç tane fazladan yedek shard üretileceğini","Mesh'te kaç peer olacağını","Mesajların ne kadar süre saklanacağını","Blok ödülünü"],"why":"OPTIMUM_SHARD_MULT bir yedeklilik çarpanı: kayıpları karşılayabilmek için fazladan shard üretilmesini sağlıyor."},
    field: {"q":"RLNC'de kodlu shard'lar, neyin üzerinde alınmış rastgele doğrusal kombinasyonlardır?","a":["Bir sonlu cisim (finite field)","Reel sayılar","Blockchain hash'leri","Rastgele İngilizce kelimeler"],"why":"Dokümanlarda kodlama, bir sonlu cisim üzerinde rastgele doğrusal kombinasyonlar olarak anlatılıyor. Orijinal parçaları çözmek için birbirinden bağımsız herhangi k kombinasyon yeterli."},
    recode: {"q":"Bir mump2p relay'i, mesajın tamamı eline geçmeden shard'larla ne yapabilir?","a":["Onlardan yeni bir kodlu shard üretip iletir","Mesajın tamamını çözene kadar hiçbir şey","Sadece kopyaları siler","Sadece yayıncının orijinal shard'larını iletir"],"why":"Her node, önce çözmesine gerek kalmadan elindeki shard'lardan yeni bir kodlu shard üretebilir. Oyundaki Yeniden Kodlayıcı Muriel de tam olarak bunu yapıyor."},
    thresholdfwd: {"q":"Bir mump2p relay'i yeniden kodlanmış shard'ları ne zaman iletmeye başlar?","a":["Elindeki shard sayısı iletim eşiğini geçince","Sadece bloğu çözdükten sonra","Sadece 12 saniyede bir","Sadece yayıncı isteyince"],"why":"Relay'ler, ellerindeki shard sayısı ForwardShardThreshold'u geçince yeniden kodlanmış shard'ları iletmeye başlıyor; böylece veri, mesajın tamamı beklenmeden akmaya devam ediyor."},
    rsvsrlnc: {"q":"RLNC'nin yolun ortasında yapabildiği ama klasik Reed Solomon kodlarının yapamadığı şey ne?","a":["Ara node'larda çözmeden yeniden kodlamak","Veriyi şifrelemek","Veriyi sıkıştırmak","Veriyi imzalamak"],"why":"Reed Solomon'da bir relay, veriyi yeniden kodlayabilmek için önce çözmek zorunda. RLNC'de ise relay elindekini karıştırıp hemen yoluna gönderiyor."},
    // subsea
    erasure: {"q":"Optimum'a göre RLNC, hangi kodlama türünün gelişmiş bir biçimi?","a":["Erasure coding","Hashing","Şifreleme","Sıkıştırma"],"why":"RLNC bir erasure coding türü: veri kodlu parçalara dönüştürülür ve eksik kalan parçaların yerini, birbirinden bağımsız başka herhangi parçalar doldurabilir."},
    loss: {"q":"RLNC'de kodlu bir shard yolda kaybolursa ne olur?","a":["Bağımsız başka herhangi bir shard onun yerini tutar","Aynı shard'ın tekrar gönderilmesi gerekir","Bloğun tamamı çöpe gider","Validator slash'lenir"],"why":"Birbirinden bağımsız herhangi k shard iş gördüğü için kaybolan shard'ın yerini sıradaki yeni shard alır. Belirli bir shard'ı yeniden göndermeye gerek kalmaz."},
    randomuseful: {"q":"Yeni kodlanmış rastgele bir shard, alıcının neden neredeyse her zaman işine yarar?","a":["Rastgele kombinasyonların elindekilerden bağımsız olma ihtimali çok yüksek","Her zaman ilk shard'dır","Mesajın tamamını içerir","Validator imzası taşır"],"why":"Rastgele doğrusal kombinasyonlar yüksek olasılıkla birbirinden bağımsızdır; bu yüzden yeni kodlu shard'lar bir peer'ın elindekini nadiren tekrarlar."},
    // stress
    zeroloss: {"q":"İlk A/B testlerinde Optimum, stres senaryolarındaki mesaj kaybı hakkında ne paylaştı?","a":["Sıfır mesaj kaybı","Yaklaşık %50 kayıp","Gossipsub ile aynı kayıp","Kayıp ölçülmedi"],"why":"Testnet duyurusuna göre stres senaryolarında hiç mesaj kaybı yaşanmadı."},
    // mesh
    mesh6: {"q":"mump2p'de varsayılan hedef mesh boyutu (peer sayısı) kaç?","a":["6","2","50","1"],"why":"OPTIMUM_MESH_TARGET, Gossipsub'da olduğu gibi varsayılan olarak 6 peer. Mesh Limits'te 6 ekip üyesini tamamlayınca hız bonusu alıyorsun."},
    meshmin: {"q":"Bir mump2p node'unda mesh peer sayısı kaçın altına düşünce node yeni peer aramaya başlar?","a":["4","1","6","12"],"why":"OPTIMUM_MESH_MIN varsayılan olarak 4: sayı bunun altına düşerse node yeni peer ekliyor."},
    meshmax: {"q":"Bir mump2p node'unda mesh peer sayısı kaçı geçince node budamaya başlar?","a":["12","6","24","100"],"why":"OPTIMUM_MESH_MAX varsayılan olarak 12. Mesh Limits'te ekibinin 12 kişiyle sınırlı olmasının sebebi de bu."},
    pubsub: {"q":"mump2p CLI'da bir topic üzerinden mesaj göndermek ve almak için hangi iki komut kullanılır?","a":["publish ve subscribe","push ve pull","mint ve burn","stake ve unstake"],"why":"mump2p bir pub/sub sistemi: bir topic'e publish ediyor, aynı topic'e subscribe oluyorsun."},
    // flex
    flexnodes: {"q":"Flexnode'lar nedir?","a":["RLNC kodlu frame'leri kodlayan, çözen ve ileten permissionless node'lar","Bir donanım cüzdanı","Bir NFT koleksiyonu","Ethereum execution client'ları"],"why":"Flexnode'lar, RLNC ile kodlanmış gossip frame'lerini kodlayan, çözen ve ileten permissionless node'lar. Kayıpları telafi etmek için boyutu sınırlı kodlu buffer'lar tutuyor ve mevcut client'larla birlikte çalışıyorlar."},
    flexreward: {"q":"Flexnode operatörleri ne karşılığında ödül kazanır?","a":["Bant genişliği sağlamak","GPU ile blok madenciliği yapmak","NFT tutmak","Governance oylamalarına katılmak"],"why":"Optimum, Flexnode'ları küresel bir veri hızlandırıcı ağı olarak anlatıyor; operatörler bu ağa bant genişliği sağladıkça ödül kazanıyor."},
    deram: {"q":"Optimum'un ürün yol haritasındaki DeRAM'in açılımı nedir?","a":["Decentralized Random Access Memory","Delegated Restaking Asset Manager","Decentralized Rollup Archive Module","Decoded RLNC Access Mesh"],"why":"DeRAM, gecikmeye duyarlı uygulamalar için yüksek hızlı state okuma ve yazma katmanı olarak anlatılıyor."},
    derom: {"q":"DeROM ne için tasarlanıyor?","a":["Değiştirilemez, küresel olarak sıralı arşiv depolama","Daha hızlı bir consensus client","Bir token köprüsü","Bir gas ücreti oracle'ı"],"why":"DeROM, yani Decentralized Read Only Memory, değiştirilemez ve küresel olarak sıralı bir arşiv depolama katmanı olarak anlatılıyor."},
    live: {"q":"Ürün sayfasına göre Optimum'un hangi ürünü şu an canlıda?","a":["mump2p","DeRAM","DeROM","Henüz hiçbiri"],"why":"mump2p canlıda. DeRAM ve DeROM için ise sayfada \"yakında\" yazıyor."},
    // gateway
    gwclients: {"q":"Optimum Gateway hangi client'ları mump2p'ye bağlar?","a":["Prysm, Lighthouse, Nimbus, Teku ve Lodestar","Geth, Nethermind, Besu ve Erigon","MetaMask ve Rabby","Bitcoin Core"],"why":"Gateway, Ethereum'un consensus layer client'larına hizmet veriyor. Geth ve benzerleri ise execution client; yani bambaşka bir katman."},
    gwnochange: {"q":"Consensus client'ların Optimum Gateway'i kullanmak için neyi değiştirmesi gerekir?","a":["Hiçbir şeyi, Gateway ile peer olmaları yeterli","Fork choice kurallarını","Validator key'lerini","Veritabanlarını"],"why":"Client tarafında hiçbir değişiklik gerekmiyor: Gateway onların gossip'ine subscribe oluyor, bunu RLNC mesh'i üzerinden taşıyor ve yeniden ağa aktarıyor."},
    gwnets: {"q":"Gateway hangi Ethereum ağlarını destekliyor?","a":["Hoodi ve Mainnet","Sadece Bitcoin","Sadece Solana devnet","Sadece özel zincirler"],"why":"Gateway'in yapılandırması Hoodi ve Mainnet'i destekliyor."},
    gwdedup: {"q":"Gateway aynı mesajı iki kez iletmekten nasıl kaçınıyor?","a":["Mesaj parmak izlerini kısa süre (yaklaşık bir dakika) tutan bir cache ile","Validator'lar arasında oylamayla","Her mesaj için bir onchain işlemle","Her ikinci mesajı atarak"],"why":"Gateway, hızlı hash parmak izleri kullanan ve yaklaşık bir dakikalık TTL'i olan bir cache ile tekrarlanan mesajları ayıklıyor."},
    cl: {"q":"Ethereum'da blok gossip'i hangi tür client'lar arasında yapılır?","a":["Consensus layer client'ları","Cüzdanlar","Block explorer'lar","Borsalar"],"why":"Bloklar ve attestation'lar, consensus layer client'ları arasında libp2p üzerinden gossip ile yayılıyor; Gateway de tam bu noktaya bağlanıyor."},
    // stress
    tenx: {"q":"İlk A/B testlerinde yoğun trafik altında OptimumP2P'nin gecikmesi Gossipsub'a göre nasıldı?","a":["Yaklaşık 10 kat daha düşük","Aşağı yukarı aynı","Yaklaşık 2 kat daha yüksek","Test edilmedi"],"why":"Testnet duyurusuna göre yoğun trafikte gecikme yaklaşık 10 kat daha düşüktü."},
    // blob
    fourmb: {"q":"Aynı testlerde mesajlar çok sık gelirken Gossipsub hangi mesaj boyutunda çökmeye başladı?","a":["4 MB","4 KB","400 MB","Hiç çökmedi"],"why":"Mesajlar çok sık geldiğinde Gossipsub 4 MB'ta çöktü; OptimumP2P ise 10 MB'a kadar stabil kaldı."},
    tenmb: {"q":"Aynı testlerde OptimumP2P hangi mesaj boyutuna kadar stabil kaldı?","a":["10 MB","1 KB","100 KB","1 GB"],"why":"Paylaşılan test sonuçlarında OptimumP2P 10 MB'a kadar olan mesajları sorunsuz taşıdı."},
    // mainnet
    stake15: {"q":"Testnet lansmanında OptimumP2P'yi test eden yedi validator operatörü, Ethereum stake'inin yaklaşık ne kadarını temsil ediyordu?","a":["Yaklaşık %15","Yaklaşık %1","Yaklaşık %50","Yaklaşık %90"],"why":"Testlere, toplam stake'in yaklaşık %15'ini temsil eden yedi büyük operatör katıldı."},
    benefits: {"q":"Optimum, validator'lar için aşağıdakilerden hangisini bir fayda olarak sayıyor?","a":["Daha fazla attestation ödülü","Kullanıcılar için daha yüksek gas ücreti","Daha uzun blok süreleri","Daha az validator'a ihtiyaç duyulması"],"why":"Optimum'un saydığı faydalar şunlar: daha fazla attestation ödülü, daha iyi MEV fırsatları ve daha az kaçırılan proposal. Bloklar hızlı gelince zamanında verilen oy sayısı da artıyor."},
    missed: {"q":"Daha hızlı yayılım neden daha az kaçırılan proposal demek?","a":["Proposer'ın bloğu süre dolmadan diğerlerine ulaşır","Bloklar küçülür","Validator'ların stake'i artar","Ücretler düşer"],"why":"Çok yavaş yayılan bir blok attestation penceresini kaçırabilir. Hız paradır: geç gelen veri sana ödül kaybettirir."},
    // hoodi
    medard: {"q":"RLNC'yi MIT'deki laboratuvarında birlikte icat eden ve Optimum'un kurucu ortaklarından olan kişi kim?","a":["Prof. Muriel Médard","Vitalik Buterin","Satoshi Nakamoto","Ada Lovelace"],"why":"Prof. Muriel Médard, RLNC'yi MIT'de birlikte icat edenlerden biri ve Optimum'un CEO'su."},
    // mainnet
    flp: {"q":"Optimum'un danışmanı Nancy Lynch, dağıtık sistemlerdeki hangi meşhur sonucun L'si?","a":["FLP imkânsızlık sonucu","CAP teoremi","Paxos","Proof of history"],"why":"Fischer, Lynch ve Paterson 1985'te, asenkron bir sistemde tek bir hatalı süreç bile varsa hiçbir deterministik protokolün konsensüsü garanti edemeyeceğini gösterdi. Optimum'un ekip sayfası da Lynch'in 1985 tarihli BFT ispatını ve 1988 tarihli DLS algoritmasını öne çıkarıyor."},
    slogan: {"q":"Optimum'un sözünü tamamla: \"Data movement sets the ceiling. ...\"","a":["Optimum raises it.","Blockchains break it.","Validators ignore it.","Fees decide it."],"why":"\"Data movement sets the ceiling. Optimum raises it.\" Yani verinin ne kadar hızlı yayıldığı, üzerine kurulan her şeyin sınırını belirliyor."},
    // hoodi
    hamming: {"q":"Prof. Muriel Médard 2026'da hangi IEEE madalyasını aldı?","a":["Richard W. Hamming Madalyası","Turing Ödülü","Fields Madalyası","Nobel Fizik Ödülü"],"why":"Hamming Madalyası, bilgi bilimlerine yapılan olağanüstü katkıları ödüllendiriyor. Ekibindeki Yeniden Kodlayıcı Muriel de adını ondan alıyor."},
    nae: {"q":"Muriel Médard hangi yıl ABD Ulusal Mühendislik Akademisi'ne seçildi?","a":["2020","1999","2010","2025"],"why":"Ekip sayfasında 2020'de Ulusal Mühendislik Akademisi'ne seçildiği yazıyor. Ayrıca IEEE'nin ve Amerikan Sanat ve Bilimler Akademisi'nin de fellow'u."},
    // shard
    itsoc: {"q":"Muriel Médard daha önce hangi kuruluşun başkanlığını yaptı?","a":["IEEE Information Theory Society","Ethereum Foundation","Linux Foundation","Royal Society of Chemistry"],"why":"Bilgi teorisi aslında şu sorunun matematiği: ne kadar verinin taşınması gerekiyor? RLNC'nin optimize ettiği şey de tam olarak bu."},
    // mainnet
    kentclub: {"q":"Optimum'un kurucu ortağı Kent Lin (ekibindeki Flexnode Bankası) hangi kulübün başkanıydı?","a":["Harvard Blockchain Club","MIT Bitcoin Club","Stanford Crypto Society","Oxford Ethereum Society"],"why":"Kent Lin iş geliştirme, tokenomics ve fon toplama tarafına bakıyor. Optimum'dan önce GSRV'de Partner'dı."},
    // shard
    kishmeta: {"q":"Dr. Kishori Konwar, Optimum'u kurmadan önce hangi şirkette kıdemli mühendis ve bilim insanı olarak çalışıyordu?","a":["Meta","Google","Apple","Amazon"],"why":"MIT'de network coding üzerine doktora sonrası araştırma yaptı, Goldman Sachs'ta da quant olarak çalıştı. Ekibindeki Kodlayıcı Kishori adını ondan alıyor."},
    kishpostdoc: {"q":"Kishori Konwar, network coding üzerine doktora sonrası araştırmasını nerede yaptı?","a":["MIT","ETH Zurich","Caltech","Oxford"],"why":"Optimum, MIT'de yıllardır süren network coding araştırmalarının içinden çıktı."},
    // mainnet
    dls: {"q":"Optimum'un ekip sayfasına göre, Nancy Lynch'in ortak geliştirdiği DLS algoritması neyin temelini oluşturuyor?","a":["Tendermint ve Ethereum konsensüsü","Bitcoin madenciliği","Zero knowledge proof'lar","IPFS depolama"],"why":"DLS (Dwork, Lynch, Stockmeyer, 1988) kısmi senkron ağlarda konsensüsü inceledi. Proof of stake protokollerinin çoğu da tam olarak bu ortamda çalışıyor."},
    // stress
    sriram: {"q":"Optimum danışmanı Sriram Vishwanath hangi alanlarda araştırma yapıyor?","a":["Bilgi teorisi, kablosuz iletişim ve ağ bilimi","Akıllı kontrat denetimi","GPU madencilik donanımı","Sadece token tasarımı"],"why":"Stress Test aşamasındaki rehberin o. Ağır yük altında mesaj çözmek, bilgi teorisinin sahadaki hali."},
    // flood
    jeff: {"q":"2025'te kendini Optimum'un yeni topluluk yöneticisi olarak tanıtan kişi kim?","a":["Jeff (@blockchainjeff)","Vitalik Buterin","Kent Lin","Satoshi Nakamoto"],"why":"Jeff, yaklaşık sekiz yıl Web3 toplulukları kurduktan sonra ekibe katıldı. Kalabalığı dağıtan Sel Kıran Jeff de adını ondan alıyor."},
    gmum: {"q":"Optimum topluluğu \"gm\" yerine ne diyor?","a":["GMUM","GMOON","WAGMI","GN"],"why":"Optimum'un topluluk yöneticisi ilk gönderisini GMUM diye açtı, topluluk da birbirini böyle selamlıyor. Oyun da seni X'te aynı şekilde karşılıyor."},
    // hoodi
    founders: {"q":"Optimum'un üç kurucu ortağı kim?","a":["Muriel Médard, Kent Lin ve Kishori Konwar","Nancy Lynch, Sriram Vishwanath ve Jeff","Vitalik Buterin, Gavin Wood ve Joe Lubin","Muriel Médard, Nancy Lynch ve Kent Lin"],"why":"Ekip sayfasında Médard (CEO), Lin ve Konwar kurucu ortak olarak geçiyor; Nancy Lynch ile Sriram Vishwanath ise danışman."},
    // mainnet
    advisors: {"q":"Optimum'un danışman olarak gösterdiği iki profesör kim?","a":["Nancy Lynch ve Sriram Vishwanath","Muriel Médard ve Kishori Konwar","Kent Lin ve Jeff","Silvio Micali ve Dan Boneh"],"why":"Nancy, ekibinde eclipse saldırganlarını ortaya çıkaran Frenleyici; Sriram ise Stress Test aşamasında sana rehberlik ediyor."},
    // hoodi
    mitinc: {"q":"Optimum hangi üniversitedeki araştırmalardan doğdu?","a":["MIT","Harvard","Stanford","Cambridge"],"why":"Optimum, MIT'de yıllardır süren network coding araştırmalarının üzerine kuruldu ve yine MIT'de inkübe edildi."},
    // mainnet
    seed11: {"q":"Optimum, 2025'teki seed round'unda ne kadar yatırım topladı?","a":["11 milyon dolar","1 milyon dolar","110 milyon dolar","1 milyar dolar"],"why":"Optimum, 11 milyon dolarlık seed round'unu Nisan 2025'te duyurdu."},
    // shard
    nodecode: {"q":"Bir mump2p relay'i, bir şey iletmeden önce mesajı çözmek zorunda mı?","a":["Hayır, elindekini yeniden kodlayıp iletebilir","Evet, her zaman","Sadece blob'larda","Sadece mainnet'te"],"why":"Çözmeyi beklememek gecikmede büyük kazanç demek: shard'lar node'dan node'a akmaya devam ediyor."},
    // mesh
    publisher: {"q":"Yeni bir mesajı publish eden mump2p node'u, mesajın shard'larıyla ne yapar?","a":["Hemen tüm mesh peer'larına gönderir","Önce bir oylama bekler","Rastgele tek bir peer'a gönderir","Bir sonraki slot'a kadar bekletir"],"why":"Publish eden node shard'ları hemen tüm mesh peer'larına yollar. Relay'ler ise eşiği geçtikten sonra yeniden kodladıkları shard'ları iletir."},
    // shard
    innovative: {"q":"Elindeki shard'ların bir kombinasyonundan ibaret olan kodlanmış bir shard için hangisi doğru?","a":["Doğrusal bağımlıdır: yeni bilgi getirmez","İki kat daha işe yarar","Geçersizdir ve slash edilir","Tek başına çözmeye yeter"],"why":"Seni çözüme sadece doğrusal bağımsız shard'lar yaklaştırır. Aynı ekip üyesinin üst üste vurması kodlanmış bir kalkana bu yüzden neredeyse hiç işlemiyor."},
    // subsea
    rateless: {"q":"Optimum'un \"Battle of the Codes\" yazısında, önceden belirlenmiş bir yedekliliği olmayan, yani rateless diye anlatılan kod ailesi hangisi?","a":["Fountain kodları","Reed Solomon kodları","Parity bitleri","Hash fonksiyonları"],"why":"Fountain kodları rateless; Reed Solomon ise yedekliliğini baştan sabitliyor. Yazının asıl vurgusu şu: relay'lerde önce çözmeden yeniden kodlama yapabilen tek kod RLNC."},
    // flood
    ihave: {"q":"Gossipsub gibi gossip protokollerinde IHAVE mesajı ne işe yarar?","a":["Peer'ın gördüğü mesaj ID'lerini duyurur","Bloğun tamamını gönderir","Bir peer'ı banlar","Yeni bir blok önerir"],"why":"IHAVE ile sadece ID'ler gossip edilir; o mesajı kaçıran peer IWANT ile cevap verir. mump2p de aynı kontrol mesajı ailesini kullanıyor."},
    // gateway
    ssz: {"q":"Gateway'in yeniden kodladığı Ethereum konsensüs mesajları hangi serileştirme formatında?","a":["SSZ (Simple Serialize)","JSON","XML","Protocol Buffers"],"why":"Konsensüs client'ları mesajları SSZ ile kodlayıp snappy ile sıkıştırarak gossip eder. Gateway de onları yeniden kodlar ki client'lar tam beklediği formatı görsün."},
    gwtopics: {"q":"Gateway, client tarafında neye subscribe olur?","a":["Konsensüs katmanının gossip topic'lerine","Sadece cüzdan işlemlerine","Borsa emir defterlerine","Sosyal medya akışlarına"],"why":"/eth2/... gossip topic'lerini dinler, trafiği RLNC mesh'i üzerinden taşır ve yerelde tekrar ağa enjekte eder."},
    noinfra: {"q":"Optimum'a göre mump2p'yi kullanmak için validator'ların altyapısında nasıl bir değişiklik gerekiyor?","a":["Hiçbiri: altyapıda değişiklik gerekmiyor","Yeni GPU'lar","Özel bir fiber hat","İkinci bir validator anahtarı"],"why":"Optimum, validator'lara sağladığı faydaları sayarken \"altyapıda değişiklik gerekmiyor\" maddesine de yer veriyor."},
    // flex
    deramuse: {"q":"DeRAM ne tür uygulamalar için tasarlandı?","a":["Hızlı state okuma ve yazma isteyen, gecikmeye duyarlı uygulamalar","Sadece uzun vadeli soğuk depolama","Madencilik havuzları","Donanım cüzdanları"],"why":"DeRAM, gecikmeye duyarlı uygulamalar için yüksek hızlı state okuma ve yazma olarak anlatılıyor. Arşiv depolama tarafı ise DeROM'un işi."},
    // mainnet
    foundation: {"q":"Optimum'un şu cümlesini tamamla: \"Fix the foundation. ...\"","a":["Everything above it improves.","Then fork the chain.","Ignore the apps.","Raise the fees."],"why":"Buradaki temel, veri yayılımı: bloklar daha hızlı taşındığında üstündeki her katman kazanır."},
    // gateway
    layer: {"q":"Optimum, teknoloji stack'inin hangi katmanında çalışıyor?","a":["Veri yayılımı (ağ) katmanında","Sadece uygulama katmanında","Cüzdan katmanında","Token katmanında"],"why":"Optimum'un işi node'lar arasında veri taşımak. İşlem yürütmüyor, konsensüs de çalıştırmıyor."},
    // mainnet
    epoch: {"q":"Ethereum'da bir epoch kaç slot'tan oluşur?","a":["32","12","64","100"],"why":"Bir epoch, 12'şer saniyelik 32 slot'tan oluşur; bu da yaklaşık 6,4 dakika eder. Validator'lar her epoch'ta bir kez attestation yapar."},
    attest: {"q":"Bir validator her epoch'ta bir kez ne yapar?","a":["Attestation yapar: gördüğü head bloğa oy verir","GPU'larla blok kazar","Stake'ini çeker","Anahtarlarını değiştirir"],"why":"Attestation için son bloğun zamanında gelmesi gerekir. Blok geç gelirse oy da geç ya da yanlış olur, ödül de kaçar."},
    // hoodi
    hoodinet: {"q":"Hoodi nedir?","a":["Validator'lar ve staking için herkese açık bir Ethereum testnet'i","Bir Optimum token'ı","Bir layer 2 rollup","Bir donanım cüzdanı"],"why":"Hoodi, validator ve staking testleri için kurulan bir Ethereum testnet'i; bu oyunun ilk aşaması da o."},
    // blob
    blobs4844: {"q":"Blob'ları Ethereum'a hangi öneri getirdi?","a":["EIP 4844 (proto danksharding)","EIP 1559","The Merge","EIP 20"],"why":"Blob'lar, rollup'lar için eklenen büyük veri parçaları ve EIP 4844 ile geldi. Veri büyüdükçe hızlı yayılım daha da kritik hale geliyor."},
    // mainnet
    mevname: {"q":"MEV'in açılımı ne?","a":["Maximal extractable value","Minimum execution volume","Mempool encryption vault","Multi validator election"],"why":"MEV, bir bloktaki işlemlerin sıralanmasından elde edilen değer. Optimum, hızlı verinin faydaları arasında daha iyi MEV fırsatlarını da sayıyor."},
    // gateway
    swarna: {"q":"Ekibindeki Uzun Menzil keskin nişancı Swarna, adını hangi Optimum analizinin yazarından alıyor?","a":["mump2p'nin Hoodi testnet'indeki 6 kat gecikme avantajı","Ethereum yellow paper","Bitcoin white paper","Bir token unlock takvimi"],"why":"Swarnabha Sinha her Hoodi bloğunu aynı anda hem mump2p hem Gossipsub üzerinden ölçtü: yaklaşık 1 saniyeye karşı yaklaşık 150 ms çıktı."},
    // mainnet
    sajida: {"q":"Ekibindeki Çözücü Sajida, adını hangi Optimum araştırma yazısının yazarından alıyor?","a":["Ethereum'da PBS hot path'indeki belirsizliğin maliyeti","Bir NFT mint rehberi","Bir Solana validator kurulum rehberi","Optimum token whitepaper'ı"],"why":"Sajida Zouarhi, proposer builder separation'da validator'lara para kaybettirenin sadece ortalama hız olmadığını gösterdi: güvenilmez teslimat da pahalıya patlıyor."},
    // stress
    paperauthors: {"q":"OptimumP2P araştırma makalesinde yazarların çoğunun yanında hangi kurum ve konum yazıyor?","a":["Optimum, Cambridge, MA","Ethereum Foundation, Zug","Google, Mountain View","CERN, Cenevre"],"why":"On bir yazarın kurumu Cambridge, Massachusetts'teki Optimum olarak geçiyor; Sriram Vishwanath ise Georgia Tech'ten. Birçoğu bu oyunda aşamalara rehberlik ediyor."},
    // hoodi
    guides: {"q":"Aşama rehberlerinden üçü olan Nicolas Nicolaou, Har Preet Singh ve Alejandro Bergasov hangi çalışmanın ortak yazarları?","a":["OptimumP2P araştırma makalesi","Ethereum yellow paper","Gossipsub v1.0 spec'i","Bitcoin white paper"],"why":"OptimumP2P makalesi (arXiv 2508.04833), protokolü ve Gossipsub'a karşı yapılan deneyleri anlatıyor."},
    // blob
    p10mb: {"q":"OptimumP2P makalesindeki stres deneyinde Gossipsub, 10 MB'lık 100 mesajın kaçını teslim edebildi?","a":["84","100","50","12"],"why":"OptimumP2P 100 büyük mesajın hepsini teslim etti, Gossipsub ise 16'sını düşürdü."},
    // stress
    p20: {"q":"Makalede saniyede 20 mesajlık yükte Gossipsub'ın gecikmesine ne oldu?","a":["Sert şekilde kötüleşip yaklaşık 4 saniyeye çıktı","10 ms'ye düştü","Sabit kaldı","Test yapılmadı"],"why":"Gossipsub yaklaşık 4,0 saniyede tıkandı; OptimumP2P ise teslimatı yaklaşık 1,8 ile 2,0 saniye arasında tuttu."},
    // hoodi
    hoodi1s: {"q":"Hoodi analizinde Gossipsub bir bloğu ortalama ne kadar sürede yaydı?","a":["Yaklaşık 1 saniye","Yaklaşık 150 ms","Yaklaşık 12 saniye","Yaklaşık 10 ms"],"why":"mump2p ortalama yaklaşık 150 ms'de yayarken Gossipsub'da baz değer yaklaşık 1 saniyeydi. Yazıya göre bu 6 katlık fark bile temkinli bir rakam."},
    dualpath: {"q":"Optimum, Hoodi karşılaştırmasını adil kılmak için ne yaptı?","a":["Her bloğu aynı anda hem mump2p hem Gossipsub üzerinden geçirdi","Sadece gece test etti","Her protokol için farklı bloklar kullandı","Validator'lardan tahmin yürütmelerini istedi"],"why":"Her gateway, aynı bloğun iki yoldan ne zaman geldiğini birebir aynı ağ koşullarında zaman damgasıyla kaydetti."},
    // gateway
    gw30: {"q":"Hoodi ölçümünde kaç gateway node'u kullanıldı?","a":["30 (ABD, Avrupa ve Asya'ya yayılmış)","1 (tek bir veri merkezinde)","3 (hepsi Avrupa'da)","3000 (validator başına bir tane)"],"why":"Gateway'ler dünyaya yayıldığı için test kıtalar arası geçişleri de kapsadı; bu geçişlerde zirve değerler yaklaşık 200 ile 250 ms'yi buldu."},
    // stress
    variance: {"q":"Daha hızlı p95 gecikmesinin yanında Optimum, mump2p'nin yayılım varyansı için ne diyor?","a":["Gossipsub'dan yaklaşık 7 kat düşük","Aşağı yukarı aynı","Gossipsub'dan yüksek","Ölçülmemiş"],"why":"Tutarlılık önemli: validator'lar plan yaparken yavaş senaryoları hesaba katar. Varyans düştükçe slot'ta kullanılabilir süre de artar."},
    // mainnet
    apr: {"q":"Optimum'un staking çalışmasına göre yayılım gecikmesini 50 ile 150 ms arası düşürmek, büyük operatörlerin APR'sini yaklaşık ne kadar artırabilir?","a":["Yaklaşık %0,66 ile %1,97 arası","Yaklaşık %50","Ölçülebilir bir fark yok","Yaklaşık %0,001"],"why":"Slot'ta daha fazla kullanılabilir süre, proposer'ların daha çok builder teklifi görmesini sağlar ve head vote doğruluğunu artırır. Kısacası hız para demek."},
    per50: {"q":"Aynı çalışmaya göre slot'ta kullanılabilir süreye eklenen her 50 ms, ortalama validator gelirini kabaca ne kadar artırıyor?","a":["Yaklaşık %0,6 ile %0,7 arası","Yaklaşık %6 ile %7 arası","Yaklaşık %60","Hiç artırmıyor"],"why":"En büyük etken MEV teklif seçimi: proposer biraz daha uzun bekleyebilirse daha yüksek değerli bir blok seçebilir."},
    headvote: {"q":"Çalışmaya göre ağ genelinde head vote doğruluğu bugün hangi seviyede?","a":["Yaklaşık %98,6","Yaklaşık %50","Yaklaşık %75","Tam %100"],"why":"Gecikme 50 ile 150 ms arası düşerse bu oran yaklaşık %98,8 ile %99,1 arasına çıkıyor; bu da ağ genelinde yılda yaklaşık 1000 ile 2000 ETH ediyor."},
    free: {"q":"Ağustos 2026 itibarıyla Optimum, beacon blok ve attestation'ları daha hızlı yaymak için validator'lardan ne kadar ücret alıyor?","a":["Hiç almıyor; ücretsiz ve Optimum'a göre ücretsiz kalacak","Blok başına ücret","Aylık abonelik","Staking ödüllerinden pay"],"why":"Optimum'un Ağustos 2026 yazısında, daha hızlı blok ve attestation erişiminin validator'lar için ücretsiz olduğu ve öyle kalacağı yazıyor."},
    // gateway
    extra: {"q":"mump2p, Ethereum'daki normal Gossipsub'ın yerini mi alıyor?","a":["Hayır, standart gossip'in yanında ek bir kanal olarak çalışıyor","Evet, Gossipsub'ı kapatıyor","Sadece hafta sonları","Sadece blob'larda"],"why":"Validator'lar standart gossip'i bırakmıyor, üstüne ikinci ve daha hızlı bir yol kazanıyor. Yollardan biri yavaşlasa bile hiçbir şey bozulmuyor."},
    console: {"q":"Ağustos 2026 yazısına göre bir validator, gateway'ini Optimum ağına nasıl bağlıyor?","a":["Optimum Console'dan aldığı bir API key ile","Bir token stake ederek","Ethereum'un konsensüs kurallarını değiştirerek","Postayla bir donanım anahtarı yollayarak"],"why":"Gateway, Optimum Console'da oluşturulan bir API key ile ağa katılıyor. Ağustos 2026 yazısına göre Console bir sonraki ay herkese açılacaktı."},
    // flex
    permissioned: {"q":"Ağustos 2026'da Optimum ağı hangi aşamadaydı?","a":["Permissioned aşamada: 40'tan fazla validator ve node operatörü, hedef permissionless","Tamamen permissionless","Kapatılmıştı","Sadece kapalı bir laboratuvar testi"],"why":"Optimum, kurumsal seviyede operatörlerle permissioned bir başlangıç yaptığını ve yol haritasının permissionless bir Optimum Network'e uzandığını anlatıyor."},
    widernet: {"q":"Optimum'a göre bir RLNC ağına daha çok node katıldıkça yayılım nasıl etkilenir?","a":["Hızlanır, çünkü node'lar kodlanmış kapasite ve kapsama ekler","Yavaşlar ve ağırlaşır","Hiçbir şey değişmez","Çalışmaz hale gelir"],"why":"Gossip'te node sayısı arttıkça kopya mesajlar da artabilir. RLNC'de ise her yeni node işe yarar kodlanmış kapasite getirir."},
    latmarket: {"q":"Flexnode operatörleri nasıl ödüllendirilecek?","a":["Sağladıkları bant genişliği için bir gecikme pazarı (latency marketplace) üzerinden","Proof of work madenciliğiyle","NFT telifleriyle","Ödül almıyorlar"],"why":"Validator'lar daha hızlı teslimat için ödeme yapıyor, bant genişliğini sağlayan operatörler de bundan kazanıyor."},
    flexhw: {"q":"Flexnodes yazısına göre RLNC tabanlı yayılım nasıl bir donanım gerektiriyor?","a":["Çok az şey: internete bağlı herhangi bir cihaz katılabilir","Veri merkezinde bir GPU kümesi","ASIC madenciler","Özel bir uydu bağlantısı"],"why":"Düşük gereksinim, merkeziyetsizlik hikayesinin bir parçası: çok sayıda küçük node ağa kodlanmış kapasite katabilir."},
    // stress
    solana: {"q":"Optimum, Aralık 2025'te Ethereum dışında hangi zincirin de daha hızlı veri yayılımına ihtiyacı olduğunu yazdı?","a":["Solana","Dogecoin","Litecoin","Monero"],"why":"Optimum belirli bir zincire bağlı değil; Swarnabha Sinha'nın yazısı Solana'nın da bundan neden kazançlı çıkacağını inceliyor."},
  };
})(typeof window !== 'undefined' ? window : globalThis);
